# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of your dependency files, "/" means repo root
    schedule:
      interval: "weekly"  # How often to check for updates
    open-pull-requests-limit: 5
    # Optionally, you can add ignore rules or version constraints here

